name: Request review on PRs

on:
  pull_request:
    types:
      - opened

jobs:
  request:
    name: Request reviews on opened PRs
    runs-on: ubuntu-24.04

    steps:
      - name: Create PR review request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit "$url" --add-reviewer ggoncalves17
          gh pr edit "$url" --add-reviewer GuilhermeSousa5
          gh pr edit "$url" --add-reviewer MauroJesus9
          gh pr edit "$url" --add-reviewer ralmachado

